version: "3.3"

services:
  stack-sculptor:
    platform: linux/amd64
    image: sighupio/stack-sculptor
    hostname: toolbox-$USER
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER: $USER
    network_mode: host
    tty: true
    volumes:
      - ${REPODIR:-.}:/src
      - $HOME/.ssh:/home/sighup/.ssh
      - $HOME/.aws:/home/sighup/.aws
    working_dir: /src
    #user: "0"
